import test from 'node:test';import assert from 'node:assert/strict';import fs from 'node:fs';import {DatabaseSync} from 'node:sqlite';
import {MOODS,QUALITIES,chord,generate,realize,palette,pitchSpelling} from '../public/harmony-v2.js';import {snapshot,emptyWorkspace,validateWorkspace} from '../public/model.js';import {musicXML} from '../public/score.js';import worker from '../server/worker.js';
const settings={tonic:0,mode:'major',mood:'brake',color:1,length:8,tempo:78,pattern:'arp'};
test('exact requested brake and chromatic chords retain their defining tones at every richness',()=>{for(let color=0;color<3;color++){assert.deepEqual(chord('brake',0,'major',color).notes,['F♯','A','C','E']);assert.deepEqual(chord('line7',0,'major',color).notes,['A','C','E','G']);assert.deepEqual(chord('lineMaj',0,'major',color).notes,['A','C','E','G♯']);assert.deepEqual(chord('lineSus',0,'major',color).notes,['D','G','A']);}});
test('all worlds produce valid 4–8 chord phrases in every key with consistent voicings',()=>{for(let tonic=0;tonic<12;tonic++)for(const mode of ['major','minor'])for(const {id:mood}of MOODS)for(let length=4;length<=8;length++)for(let variant=0;variant<5;variant++){const s={...settings,tonic,mode,mood,length,color:variant%3},p={...s,...generate(s,variant)};assert.equal(p.ids.length,length);for(const c of realize(p)){assert.equal(c.midi[0]%12,c.bass);assert.ok(c.midi.every(n=>Number.isFinite(n)&&n>=33&&n<=84&&c.pcs.includes(n%12)));for(const midi of c.midi){const n=pitchSpelling(midi,c),natural={C:0,D:2,E:4,F:5,G:7,A:9,B:11};assert.equal((n.octave+1)*12+natural[n.step]+n.alter,midi);}}}});
test('all chord color overrides are explicit valid pitch sets',()=>{for(const id of palette())for(const quality of Object.keys(QUALITIES)){const c=chord(id+':'+quality,1,'major',2,'rnb');assert.ok(c.notes.every(n=>!n.includes('undefined')));assert.ok(realize({...settings,ids:[c.id]})[0].midi.length>=4);}});
test('score snapshots keep their pitches when editor settings change; MusicXML aligns both staves',()=>{const p=snapshot({...settings,ids:['line7','lineMaj','lineSus','brake']},'Brake & <release>');const stored=JSON.stringify(p);settings.tonic=2;assert.equal(JSON.stringify(p),stored);settings.tonic=0;const q=snapshot({...settings,tonic:1,mode:'major',ids:['d0','t3','d3','d4']},'Flat-key phrase'),xml=musicXML({name:'Test & tune',sections:[p,q]});assert.equal((xml.match(/<measure number=/g)||[]).length,8);assert.equal((xml.match(/<backup><duration>16<\/duration><\/backup>/g)||[]).length,8);assert.ok(xml.includes('<step>G</step><alter>1</alter>'));assert.ok(xml.includes('<fifths>-5</fifths>'));assert.ok(xml.includes('Test &amp; tune'));assert.ok(xml.includes('Brake &amp; &lt;release&gt;'));assert.ok(xml.includes('<kind text="m(maj7)">major-minor</kind>'));});
function db(){const sqlite=new DatabaseSync(':memory:');for(const f of fs.readdirSync('drizzle').filter(f=>f.endsWith('.sql')))sqlite.exec(fs.readFileSync('drizzle/'+f,'utf8'));return{prepare(sql){return{bind(...args){const stmt=sqlite.prepare(sql);return{first:async()=>stmt.get(...args),run:async()=>({meta:{changes:Number(stmt.run(...args).changes)}})};}};}};}
test('persistent API protects ownership, revisions and invalid writes',async()=>{const env={DB:db()},call=(method,data,user='owner',origin='https://studio.test')=>worker.fetch(new Request('https://studio.test/api/workspace',{method,headers:{...(user?{'oai-authenticated-user-id':user}:{}),'Content-Type':'application/json',Origin:origin},...(data?{body:JSON.stringify(data)}:{})}),env);assert.equal((await call('GET',null,null)).status,401);const data=emptyWorkspace(),p=snapshot({...settings,ids:generate(settings).ids},'Saved idea');data.favorites=[p];data.scores=[{id:'score-1',name:'My song',sections:[{...p,id:'phrase-1'},{...p,id:'phrase-2'}]}];data.activeScoreId='score-1';validateWorkspace(data);assert.equal((await call('PUT',{revision:0,data})).status,200);let saved=await(await call('GET')).json();assert.equal(saved.revision,1);assert.equal(saved.data.scores[0].sections.length,2);assert.equal((await call('PUT',{revision:0,data})).status,409);assert.equal((await call('PUT',{revision:1,data},'owner','https://attacker.test')).status,403);assert.equal((await(await call('GET',null,'another-owner')).json()).data.favorites.length,0);const bad=structuredClone(data);bad.favorites[0].ids=['bad'];assert.equal((await call('PUT',{revision:1,data:bad})).status,400);saved=await(await call('GET')).json();assert.equal(saved.revision,1);assert.equal(saved.data.favorites[0].name,'Saved idea');data.scores[0].sections.reverse();assert.equal((await call('PUT',{revision:1,data})).status,200);assert.equal((await(await call('GET')).json()).data.scores[0].sections[0].id,'phrase-2');});
